service: mkflow

provider:
  name: aws
  runtime: java11
  memorySize: 1024
  stage: ${opt:stage, 'staging'}
  region: us-east-1
  timeout: 900
  versionFunctions: false
  tracing:
  environment:
    QUARKUS_PROFILE: ${opt:stage, 'staging'}
    DISABLE_SIGNAL_HANDLERS: true
  logRetentionInDays: 365
  deploymentBucket:
    serverSideEncryption: AES256
  iam:
    role:
      statements:
        - Effect: 'Allow' # Glue Access
          Action:
            - "glue:*"
          "Resource": "*"
        - Effect: 'Allow' # Glue Access0
          Action:
            - "lambda:InvokeFunction"
          "Resource": "arn:aws:lambda:*:*:function:mkflow-*"



package:
  artifact: target/function.zip

functions:
  api:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

